Importo las librerias que son necesarias para Generar el ETL

In [100]:
import pandas as pd
import ast
import json
import parquet

Leo el JSON output_steam_games

In [101]:
# Importar el Data set
dataset = pd.read_json('output_steam_games.json', lines=True)

Leo el dataframe para ver que corrio bien

In [5]:
dataset

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
1,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
2,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
3,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
4,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,0.0,773640.0,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,0.0,733530.0,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,0.0,610660.0,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,0.0,658870.0,"xropi,stev3ns"
120444,None,None,Maze Run VR,None,http://store.steampowered.com/app/681550/Maze_...,None,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,1.0,681550.0,None

Veo la forma del dataset con Shape

In [6]:
dataset.shape

(120445, 13)

Analizo si hay ID repetidas

In [7]:
call_id_counts = dataset['id'].value_counts()
call_id_counts

id
612880.0    2
761140.0    1
530200.0    1
518690.0    1
513460.0    1
           ..
676060.0    1
494160.0    1
215280.0    1
667090.0    1
681550.0    1
Name: count, Length: 32132, dtype: int64

Verifico cuantas se repiten

In [80]:
id_mas_de_una_vez = call_id_counts[call_id_counts > 1].index.tolist()

print(id_mas_de_una_vez)

[612880.0]

Busco las filas que tienen los ID repetidos para su analisis

In [81]:
fila_resultado = dataset[dataset['id'] == 612880.0]
fila_resultado

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
102204,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,"[Single-player, Steam Achievements, Full contr...",59.99,0.0,612880.0,Machine Games
102883,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/Wolfe...,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,"[Single-player, Steam Achievements, Full contr...",59.99,0.0,612880.0,Machine Games

Al ver que son el mismo elemento repetido, procedo con la eliminacion de una de ellas

In [102]:
dataset = dataset.drop(102883)

Ya se encuentra sin repetidos el dataset

In [103]:
fila_resultado = dataset[dataset['id'] == 612880.0]
fila_resultado

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
102204,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,"[Single-player, Steam Achievements, Full contr...",59.99,0.0,612880.0,Machine Games

Ahora procedo a eliminar los NAN de las primeras filas(obtuve el resultado viendo hasta donde llegaban estas filas vacias en el CSV)

In [104]:
dataset = dataset.dropna()

In [9]:
dataset = dataset.drop(range(0, 88384))

In [105]:
dataset

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
88310,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,0.0,761140.0,Kotoshiro
88311,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,2018-01-04,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free To Play,0.0,643980.0,Secret Level SRL
88312,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,2017-07-24,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free to Play,0.0,670290.0,Poolians.com
88313,彼岸领域,"[Action, Adventure, Casual]",弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,2017-12-07,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,0.0,767400.0,彼岸领域
88315,Trickjump Games Ltd,"[Action, Adventure, Simulation]",Battle Royale Trainer,Battle Royale Trainer,http://store.steampowered.com/app/772540/Battl...,2018-01-04,"[Action, Adventure, Simulation, FPS, Shooter, ...",http://steamcommunity.com/app/772540/reviews/?...,"[Single-player, Steam Achievements]",3.99,0.0,772540.0,Trickjump Games Ltd
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120439,Bidoniera Games,"[Action, Adventure, Casual, Indie]",Kebab it Up!,Kebab it Up!,http://store.steampowered.com/app/745400/Kebab...,2018-01-04,"[Action, Indie, Casual, Violent, Adventure]",http://steamcommunity.com/app/745400/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",1.99,0.0,745400.0,Bidoniera Games
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,0.0,773640.0,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,0.0,733530.0,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,0.0,610660.0,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,0.0,658870.0,"xropi,stev3ns"

Se eliminan las columnas que no son necesarias

In [106]:
dataset.drop(['title',	'url',	'tags', 'specs', 'early_access', 'reviews_url'], axis=1, inplace=True)

In [127]:
dataset

,publisher,genres,app_name,release_date,price,id,developer
88384,None,None,None,None,19.99,NaN,None
88385,2K Games,[Strategy],Railroad Tycoon II Platinum,1998-10-31,4.99,7620.0,PopTop
88386,None,"[Casual, Indie]",RIP - Trilogy™,2007-06-01,4.99,2540.0,Elephant Games
88387,2K Games,[Strategy],X-COM: Terror From the Deep,1995-04-01,4.99,7650.0,"MicroProse Software, Inc"
88388,"Square Enix, Feral Interactive (Mac)","[Action, Adventure]",Tomb Raider: Anniversary,2007-06-05,8.99,8000.0,"Crystal Dynamics,Feral Interactive (Mac)"
...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,2018-01-04,1.99,773640.0,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,2018-01-04,4.99,733530.0,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,2018-01-04,1.99,610660.0,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,2017-09-02,4.99,658870.0,"xropi,stev3ns"
120444,None,None,Maze Run VR,None,4.99,681550.0,None

Eliminamos los nulos

In [11]:
dataset = dataset.dropna()

In [107]:
dataset

,publisher,genres,app_name,release_date,price,id,developer
88310,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,2018-01-04,4.99,761140.0,Kotoshiro
88311,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,2018-01-04,Free To Play,643980.0,Secret Level SRL
88312,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,2017-07-24,Free to Play,670290.0,Poolians.com
88313,彼岸领域,"[Action, Adventure, Casual]",弹炸人2222,2017-12-07,0.99,767400.0,彼岸领域
88315,Trickjump Games Ltd,"[Action, Adventure, Simulation]",Battle Royale Trainer,2018-01-04,3.99,772540.0,Trickjump Games Ltd
...,...,...,...,...,...,...,...
120439,Bidoniera Games,"[Action, Adventure, Casual, Indie]",Kebab it Up!,2018-01-04,1.99,745400.0,Bidoniera Games
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,2018-01-04,1.99,773640.0,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,2018-01-04,4.99,733530.0,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,2018-01-04,1.99,610660.0,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,2017-09-02,4.99,658870.0,"xropi,stev3ns"

In [108]:
dataset.rename(columns={'id': 'item_id'}, inplace=True)

Convierte todos los valores de tipo cadena a 0 en la columna especificada

In [109]:
columna_a_convertir = 'price'

dataset.loc[dataset[columna_a_convertir].apply(lambda x: isinstance(x, str)), columna_a_convertir] = 0

In [110]:
dataset.to_parquet('output.parquet', index=False)

Genero un CSV desde el Dataframe

In [136]:
dataset.to_csv('output.csv', index=False)

Leo el JSON australian_user_items

In [43]:
data_list = []

In [44]:
#Ruta del archivo JSON
file_path = 'australian_users_items.json'

#Abrir el archivo y procesar cada línea
with open(file_path, 'r', encoding='utf-8') as file:
    for line in file:
        try:
            # Usar ast.literal_eval para convertir la línea en un diccionario
            json_data = ast.literal_eval(line)
            data_list.append(json_data)
        except ValueError as e:
            print(f"Error en la línea: {line}")
            continue

#Crear un DataFrame a partir de la lista de diccionarios
data_it = pd.DataFrame(data_list)

In [148]:
data_it

,item_id,item_name,playtime_forever,playtime_2weeks,user_id,items_count,steam_id,user_url,items
0,10.0,Counter-Strike,6.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '10', 'item_name': 'Counter-Strike..."
1,20.0,Team Fortress Classic,0.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '20', 'item_name': 'Team Fortress ..."
2,30.0,Day of Defeat,7.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '30', 'item_name': 'Day of Defeat'..."
3,40.0,Deathmatch Classic,0.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '40', 'item_name': 'Deathmatch Cla..."
4,50.0,Half-Life: Opposing Force,0.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '50', 'item_name': 'Half-Life: Opp..."
...,...,...,...,...,...,...,...,...,...
7411032,292030.0,The Witcher 3: Wild Hunt,2331.0,0.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '292030', 'item_name': 'The Witche..."
7411033,377160.0,Fallout 4,18839.0,1143.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '377160', 'item_name': 'Fallout 4'..."
7411034,299360.0,Block N Load,234.0,0.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '299360', 'item_name': 'Block N Lo..."
7411035,50130.0,Mafia II,905.0,0.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '50130', 'item_name': 'Mafia II', ..."
7411036,105600.0,Terraria,201.0,0.0,Pheress,35,76561198083186121,http://steamcommunity.com/id/Pheress,"{'item_id': '105600', 'item_name': 'Terraria',..."

Se desanidan los datos de la columna ['items']

In [45]:
data_it1 = data_it.explode(['items'])
data_it2 = pd.json_normalize(data_it1['items']).set_index(data_it1['items'].index)
data_it3= pd.concat([data_it2, data_it1], axis=1)

In [154]:
data_it3

,item_id,item_name,playtime_forever,playtime_2weeks,user_id,items_count,steam_id,user_url,items
0,10.0,Counter-Strike,6.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '10', 'item_name': 'Counter-Strike..."
1,20.0,Team Fortress Classic,0.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '20', 'item_name': 'Team Fortress ..."
2,30.0,Day of Defeat,7.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '30', 'item_name': 'Day of Defeat'..."
3,40.0,Deathmatch Classic,0.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '40', 'item_name': 'Deathmatch Cla..."
4,50.0,Half-Life: Opposing Force,0.0,0.0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '50', 'item_name': 'Half-Life: Opp..."
...,...,...,...,...,...,...,...,...,...
7411032,292030.0,The Witcher 3: Wild Hunt,2331.0,0.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '292030', 'item_name': 'The Witche..."
7411033,377160.0,Fallout 4,18839.0,1143.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '377160', 'item_name': 'Fallout 4'..."
7411034,299360.0,Block N Load,234.0,0.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '299360', 'item_name': 'Block N Lo..."
7411035,50130.0,Mafia II,905.0,0.0,76561198058580105,145,76561198058580105,http://steamcommunity.com/profiles/76561198058...,"{'item_id': '50130', 'item_name': 'Mafia II', ..."
7411036,105600.0,Terraria,201.0,0.0,Pheress,35,76561198083186121,http://steamcommunity.com/id/Pheress,"{'item_id': '105600', 'item_name': 'Terraria',..."

Se eliminan las columnas que no se consideran relevantes para el posterior analisis

In [46]:
data_it3.drop(['items_count','user_url','item_name','steam_id'], axis=1, inplace=True)

Se eliminan los datos nulos por columnas

In [47]:
data_it3 = data_it3.dropna(subset=['item_id'])
data_it3 = data_it3.dropna(subset=['playtime_forever'])

Se eliminan 2 columnas adicionales

In [48]:
data_it3.drop(['items','playtime_2weeks'], axis=1, inplace=True)

Se define el dataframe solo para aquellos juegos donde tuvieron un tiempo jugado (condicion)

In [49]:
data_it3 = data_it3[data_it3['playtime_forever'] != 0]

Se conservan las 3 columnas para el analisis

In [50]:
data_it3 = data_it3[['user_id','item_id','playtime_forever']]

Creo el archivo en formato parquet para reduccion de peso

In [52]:
data_it3.to_parquet('user_items.parquet', index= False)

Se exporta la tabla como archivo separa por comas de nombre 'user_items'

In [51]:
data_it3.to_csv('user_items.csv', index=False)

Leo el JSON australian_user_items

In [55]:
data_list1 = []

In [56]:
#Ruta del archivo JSON
file_path = 'australian_user_reviews.json'

#Abrir el archivo y procesar cada línea
with open(file_path, 'r', encoding='utf-8') as file:
    for line in file:
        try:
            # Usar ast.literal_eval para convertir la línea en un diccionario
            json_data = ast.literal_eval(line)
            data_list1.append(json_data)
        except ValueError as e:
            print(f"Error en la línea: {line}")
            continue

#Crear un DataFrame a partir de la lista de diccionarios
data_it = pd.DataFrame(data_list1)

In [177]:
data_it

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."
...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la..."
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l..."
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',..."
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l..."
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',..."

Se desanidan los datos de la columna ['reviews']

In [57]:
data_it1 = data_it.explode(['reviews'])
data_it2 = pd.json_normalize(data_it1['reviews']).set_index(data_it1['reviews'].index)
data_it3= pd.concat([data_it2, data_it1], axis=1)

In [174]:
data_it3

,funny,posted,last_edited,item_id,helpful,recommend,review,user_id,user_url,reviews
0,,"Posted November 5, 2011.",,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'funny': '', 'posted': 'Posted November 5, 20..."
0,,"Posted July 15, 2011.",,22200,No ratings yet,True,It's unique and worth a playthrough.,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'funny': '', 'posted': 'Posted July 15, 2011...."
0,,"Posted April 21, 2011.",,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'funny': '', 'posted': 'Posted April 21, 2011..."
1,,"Posted June 24, 2014.",,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,js41637,http://steamcommunity.com/id/js41637,"{'funny': '', 'posted': 'Posted June 24, 2014...."
1,,"Posted September 8, 2013.",,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...,js41637,http://steamcommunity.com/id/js41637,"{'funny': '', 'posted': 'Posted September 8, 2..."
...,...,...,...,...,...,...,...,...,...,...
25797,,Posted July 10.,,70,No ratings yet,True,a must have classic from steam definitely wort...,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"{'funny': '', 'posted': 'Posted July 10.', 'la..."
25797,,Posted July 8.,,362890,No ratings yet,True,this game is a perfect remake of the original ...,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"{'funny': '', 'posted': 'Posted July 8.', 'las..."
25798,1 person found this review funny,Posted July 3.,,273110,1 of 2 people (50%) found this review helpful,True,had so much fun plaing this and collecting res...,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"{'funny': '1 person found this review funny', ..."
25798,,Posted July 20.,,730,No ratings yet,True,:D,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"{'funny': '', 'posted': 'Posted July 20.', 'la..."
25798,,Posted July 2.,,440,No ratings yet,True,so much fun :D,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"{'funny': '', 'posted': 'Posted July 2.', 'las..."

Se eliminan las columnas que no se consideran relevantes para el posterior analisis

In [58]:
data_it3.drop(['funny','last_edited','helpful','user_url'], axis=1, inplace=True)

In [167]:
data_it3

,posted,item_id,recommend,review,user_id,reviews
0,"Posted November 5, 2011.",1250,True,Simple yet with great replayability. In my opi...,76561197970982479,"{'funny': '', 'posted': 'Posted November 5, 20..."
0,"Posted July 15, 2011.",22200,True,It's unique and worth a playthrough.,76561197970982479,"{'funny': '', 'posted': 'Posted July 15, 2011...."
0,"Posted April 21, 2011.",43110,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,"{'funny': '', 'posted': 'Posted April 21, 2011..."
1,"Posted June 24, 2014.",251610,True,I know what you think when you see this title ...,js41637,"{'funny': '', 'posted': 'Posted June 24, 2014...."
1,"Posted September 8, 2013.",227300,True,For a simple (it's actually not all that simpl...,js41637,"{'funny': '', 'posted': 'Posted September 8, 2..."
...,...,...,...,...,...,...
25797,Posted July 10.,70,True,a must have classic from steam definitely wort...,76561198312638244,"{'funny': '', 'posted': 'Posted July 10.', 'la..."
25797,Posted July 8.,362890,True,this game is a perfect remake of the original ...,76561198312638244,"{'funny': '', 'posted': 'Posted July 8.', 'las..."
25798,Posted July 3.,273110,True,had so much fun plaing this and collecting res...,LydiaMorley,"{'funny': '1 person found this review funny', ..."
25798,Posted July 20.,730,True,:D,LydiaMorley,"{'funny': '', 'posted': 'Posted July 20.', 'la..."
25798,Posted July 2.,440,True,so much fun :D,LydiaMorley,"{'funny': '', 'posted': 'Posted July 2.', 'las..."

Se eliminan los datos nulos por columnas

In [59]:
#se eliminan los datos nulos por columnas
data_it3 = data_it3.dropna(subset=['posted'])
data_it3 = data_it3.dropna(subset=['item_id'])

In [170]:
data_it3

,posted,item_id,recommend,review,user_id,reviews
0,"Posted November 5, 2011.",1250,True,Simple yet with great replayability. In my opi...,76561197970982479,"{'funny': '', 'posted': 'Posted November 5, 20..."
0,"Posted July 15, 2011.",22200,True,It's unique and worth a playthrough.,76561197970982479,"{'funny': '', 'posted': 'Posted July 15, 2011...."
0,"Posted April 21, 2011.",43110,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,"{'funny': '', 'posted': 'Posted April 21, 2011..."
1,"Posted June 24, 2014.",251610,True,I know what you think when you see this title ...,js41637,"{'funny': '', 'posted': 'Posted June 24, 2014...."
1,"Posted September 8, 2013.",227300,True,For a simple (it's actually not all that simpl...,js41637,"{'funny': '', 'posted': 'Posted September 8, 2..."
...,...,...,...,...,...,...
25797,Posted July 10.,70,True,a must have classic from steam definitely wort...,76561198312638244,"{'funny': '', 'posted': 'Posted July 10.', 'la..."
25797,Posted July 8.,362890,True,this game is a perfect remake of the original ...,76561198312638244,"{'funny': '', 'posted': 'Posted July 8.', 'las..."
25798,Posted July 3.,273110,True,had so much fun plaing this and collecting res...,LydiaMorley,"{'funny': '1 person found this review funny', ..."
25798,Posted July 20.,730,True,:D,LydiaMorley,"{'funny': '', 'posted': 'Posted July 20.', 'la..."
25798,Posted July 2.,440,True,so much fun :D,LydiaMorley,"{'funny': '', 'posted': 'Posted July 2.', 'las..."

Se eliminan 2 columnas adicionales

In [60]:
data_it3.drop(['reviews'], axis=1, inplace=True)

Se define el dataframe solo para aquellos juegos donde tuvieron un tiempo jugado (condicion)

In [61]:
#se define el dataframe solo para aquellos juegos donde tuvieron un tiempo jugado (condicion)
data_it3 = data_it3[data_it3['item_id'] != 0]

In [184]:
data_it3

,posted,item_id,recommend,review,user_id
0,"Posted November 5, 2011.",1250,True,Simple yet with great replayability. In my opi...,76561197970982479
0,"Posted July 15, 2011.",22200,True,It's unique and worth a playthrough.,76561197970982479
0,"Posted April 21, 2011.",43110,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479
1,"Posted June 24, 2014.",251610,True,I know what you think when you see this title ...,js41637
1,"Posted September 8, 2013.",227300,True,For a simple (it's actually not all that simpl...,js41637
...,...,...,...,...,...
25797,Posted July 10.,70,True,a must have classic from steam definitely wort...,76561198312638244
25797,Posted July 8.,362890,True,this game is a perfect remake of the original ...,76561198312638244
25798,Posted July 3.,273110,True,had so much fun plaing this and collecting res...,LydiaMorley
25798,Posted July 20.,730,True,:D,LydiaMorley
25798,Posted July 2.,440,True,so much fun :D,LydiaMorley

Se eliminan los duplicados y valores nulos en caso de haber

In [62]:
data_it3 = data_it3.drop_duplicates()
data_it3 = data_it3.dropna()

In [63]:
data_it3.to_parquet('user_reviews.parquet', index=False)

Se exporta la tabla como archivo separa por comas de nombre 'user_Reviews'

In [186]:
#se exporta la tabla como archivo separa por comas de nombre 'user_items'
data_it3.to_csv('user_reviews.csv', index=False)

Se crea el analisis de sentimiento sobre la columna review

In [66]:
from textblob import TextBlob

In [67]:
def analyze_sentiment(review):
    analysis = TextBlob(str(review))
    # Asigna un valor según el análisis de sentimiento
    if analysis.sentiment.polarity > 0.1: 
        return 2  # Positivo
    elif analysis.sentiment.polarity < -0.1:
        return 0  # Malo
    else:
        return 1  # Neutral

Se agrega la columna Sentiment_analysis

In [68]:
data_it3['Sentiment_analysis'] = data_it3['review'].apply(analyze_sentiment)

In [69]:
data_it3

,posted,item_id,recommend,review,user_id,Sentiment_analysis
0,"Posted November 5, 2011.",1250,True,Simple yet with great replayability. In my opi...,76561197970982479,2
0,"Posted July 15, 2011.",22200,True,It's unique and worth a playthrough.,76561197970982479,2
0,"Posted April 21, 2011.",43110,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,1
1,"Posted June 24, 2014.",251610,True,I know what you think when you see this title ...,js41637,2
1,"Posted September 8, 2013.",227300,True,For a simple (it's actually not all that simpl...,js41637,1
...,...,...,...,...,...,...
25797,Posted July 10.,70,True,a must have classic from steam definitely wort...,76561198312638244,2
25797,Posted July 8.,362890,True,this game is a perfect remake of the original ...,76561198312638244,2
25798,Posted July 3.,273110,True,had so much fun plaing this and collecting res...,LydiaMorley,1
25798,Posted July 20.,730,True,:D,LydiaMorley,2
25798,Posted July 2.,440,True,so much fun :D,LydiaMorley,2

In [70]:
data_it3.to_parquet('user_reviews.parquet', index=False)

Se vuelve a crear el CSV

In [193]:
data_it3.to_csv('user_reviews.csv', index=False)

Volvemos a llamar a los CSV para la creacion de una tabla unica con un JOIN

In [84]:
dfgames = pd.read_csv('output.csv')
dfitems = pd.read_csv('user_items.csv')
dfreviews = pd.read_csv('user_reviews.csv')

Volvemos a chequear si hay datos faltantes

In [85]:
dfgames = dfgames.dropna()

In [86]:
dfitems = dfitems.dropna()

In [87]:
dfreviews = dfreviews.dropna()

Uni los Datasets de Users

In [88]:
df_merge = pd.merge(dfitems,dfreviews, how="inner")

In [76]:
df_merge

,user_id,item_id,playtime_forever,posted,recommend,review,Sentiment_analysis
0,76561197970982479,22200,271.0,"Posted July 15, 2011.",True,It's unique and worth a playthrough.,2
1,76561197970982479,1250,10006.0,"Posted November 5, 2011.",True,Simple yet with great replayability. In my opi...,2
2,76561197970982479,43110,834.0,"Posted April 21, 2011.",True,Great atmosphere. The gunplay can be a bit chu...,1
3,js41637,227300,551.0,"Posted September 8, 2013.",True,For a simple (it's actually not all that simpl...,1
4,js41637,239030,349.0,"Posted November 29, 2013.",True,Very fun little game to play when your bored o...,1
...,...,...,...,...,...,...,...
44799,Ghoustik,730,3969.0,Posted June 17.,True,Gra naprawdę fajna.Ale jest kilka rzeczy do kt...,1
44800,76561198312638244,70,1010.0,Posted July 10.,True,a must have classic from steam definitely wort...,2
44801,76561198312638244,130,221.0,Posted July 10.,True,if you liked Half life i would really recommen...,2
44802,76561198312638244,233270,533.0,Posted July 21.,True,this is a very fun and nice 80s themed shooter...,2
44803,76561198312638244,362890,2184.0,Posted July 8.,True,this game is a perfect remake of the original ...,2

Renombro la columna id de output por item_id para que se pueda relacionar

In [89]:
dfgames.rename(columns={'id': 'item_id'}, inplace=True)

In [81]:
dfgames

,publisher,genres,app_name,release_date,price,item_id,developer
0,2K Games,[Strategy],Railroad Tycoon II Platinum,1998-10-31,4.99,7620.0,PopTop
1,2K Games,[Strategy],X-COM: Terror From the Deep,1995-04-01,4.99,7650.0,"MicroProse Software, Inc"
2,"Square Enix, Feral Interactive (Mac)","[Action, Adventure]",Tomb Raider: Anniversary,2007-06-05,8.99,8000.0,"Crystal Dynamics,Feral Interactive (Mac)"
3,Capcom,[Action],Devil May Cry® 3 Special Edition,2006-05-23,19.99,6550.0,"CAPCOM Co., Ltd."
4,Telltale Games,"[Action, Adventure]",Sam & Max 101: Culture Shock,2006-10-17,19.99,8200.0,Telltale Games
...,...,...,...,...,...,...,...
22762,Bidoniera Games,"[Action, Adventure, Casual, Indie]",Kebab it Up!,2018-01-04,1.99,745400.0,Bidoniera Games
22763,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,2018-01-04,1.99,773640.0,"Nikita ""Ghost_RUS"""
22764,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,2018-01-04,4.99,733530.0,Sacada
22765,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,2018-01-04,1.99,610660.0,Laush Dmitriy Sergeevich
22766,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,2017-09-02,4.99,658870.0,"xropi,stev3ns"

In [90]:
df_merge = pd.merge(dfgames,df_merge, how="inner")

In [204]:
df_merge

,publisher,genres,app_name,release_date,price,item_id,developer,user_id,playtime_forever,posted,recommend,review,Sentiment_analysis
0,"Square Enix, Feral Interactive (Mac)","['Action', 'Adventure']",Tomb Raider: Anniversary,2007-06-05,8.99,8000.0,"Crystal Dynamics,Feral Interactive (Mac)",76561198052998873,378.0,"Posted December 11, 2015.",True,"One of the best games of all time, I have been...",2
1,Capcom,['Action'],Devil May Cry® 3 Special Edition,2006-05-23,19.99,6550.0,"CAPCOM Co., Ltd.",ryanflyin13,2872.0,Posted June 4.,True,This game made a huge impact on my life when i...,1
2,Capcom,['Action'],Devil May Cry® 3 Special Edition,2006-05-23,19.99,6550.0,"CAPCOM Co., Ltd.",ryanflyin13,2872.0,Posted June 4.,True,This game made a huge impact on my life when i...,1
3,Capcom,['Action'],Devil May Cry® 3 Special Edition,2006-05-23,19.99,6550.0,"CAPCOM Co., Ltd.",SambaWarKiddo,47.0,"Posted May 31, 2014.",True,"Fantastic game by absolutely all means, and if...",2
4,Capcom,['Action'],Devil May Cry® 3 Special Edition,2006-05-23,19.99,6550.0,"CAPCOM Co., Ltd.",SambaWarKiddo,47.0,"Posted May 31, 2014.",True,"Fantastic game by absolutely all means, and if...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52474,Valve,['Action'],Counter-Strike: Condition Zero,2004-03-01,9.99,80.0,Valve,virex4,26740.0,"Posted December 28, 2011.",True,:D,2
52475,Valve,['Action'],Counter-Strike: Condition Zero,2004-03-01,9.99,80.0,Valve,KILLERamateur,3721.0,"Posted March 9, 2014.",True,cool. Same as the first one but the maps and w...,2
52476,Valve,['Action'],Counter-Strike: Condition Zero,2004-03-01,9.99,80.0,Valve,76561198015050660,2416.0,"Posted December 23, 2014.",False,作為第一個在steam入手的遊戲，老實說當初是為了1.6來順便帶回來，由於當時網路不太穩的關...,1
52477,Valve,['Action'],Counter-Strike: Condition Zero,2004-03-01,9.99,80.0,Valve,76561198023508728,15.0,"Posted October 26, 2014.",False,i caused 9/11,1
52478,Valve,['Action'],Counter-Strike: Condition Zero,2004-03-01,9.99,80.0,Valve,green290,442.0,"Posted January 5, 2015.",True,This game was suprisingly my first FPS game.11...,2

Se crea el CSV y se ubica en la carpeta data asi los proximos CSV se alojen en el mismo lugar

In [91]:
df_merge.to_parquet('df_merge.parquet', index=False)

In [233]:
df_merge = pd.read_csv('data/df_merge.csv', encoding='utf-8')

In [92]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36578 entries, 0 to 36577
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   publisher           36578 non-null  object
 1   genres              36578 non-null  object
 2   app_name            36578 non-null  object
 3   release_date        36578 non-null  object
 4   price               36578 non-null  object
 5   item_id             36578 non-null  float64
 6   developer           36578 non-null  object
 7   user_id             36578 non-null  object
 8   playtime_forever    36578 non-null  float64
 9   posted              36578 non-null  object
 10  recommend           36578 non-null  bool
 11  review              36578 non-null  object
 12  Sentiment_analysis  36578 non-null  int64
dtypes: bool(1), float64(2), int64(1), object(9)
memory usage: 3.4+ MB

Se cambia el tipo de dato de Free to play a 0 para poder hacer el analisis

In [234]:
df_merge['price'] = df_merge['price'].replace('Free to Play', 0)

Convertir la columna 'price' a tipo numérico y reemplazar NaN con ceros

In [93]:
# Convertir la columna 'price' a tipo numérico y reemplazar NaN con ceros
df_merge['price'] = pd.to_numeric(df_merge['price'], errors='coerce').fillna(0)

# Imprimir los valores no numéricos en la columna 'price' después de la conversión
print("Valores no numéricos en la columna 'price' después de la conversión:")
print(df_merge.loc[df_merge['price'].isnull(),'price'])

Valores no numéricos en la columna 'price' después de la conversión:
Series([], Name: price, dtype: float64)

Se configura la columna release_date a un valor de años

In [94]:
# Supongamos que 'release_date' es la columna que contiene las fechas
df_merge['release_date'] = pd.to_datetime(df_merge['release_date'], errors='coerce')

# Asegúrate de que no haya valores nulos en la columna 'release_date'
print(df_merge['release_date'].isnull().sum())

# Crea la columna 'Años' extrayendo el año después de la conversión
df_merge['Años'] = df_merge['release_date'].dt.year

# Imprime el DataFrame para verificar los resultados
print(df_merge)

186
                                  publisher                   genres  \
0      Square Enix, Feral Interactive (Mac)  ['Action', 'Adventure']
1                                    Capcom               ['Action']
2                                    Capcom               ['Action']
3                                    Capcom               ['Action']
4                                    Capcom               ['Action']
...                                     ...                      ...
36573                                 Valve               ['Action']
36574                                 Valve               ['Action']
36575                                 Valve               ['Action']
36576                                 Valve               ['Action']
36577                                 Valve               ['Action']

                               app_name release_date  price  item_id  \
0              Tomb Raider: Anniversary   2007-06-05   8.99   8000.0
1      Devil May Cry® 3 Special Edition   2006-05-23  19.99   6550.0
2      Devil May Cry® 3 Special Edition   2006-05-23  19.99   6550.0
3      Devil May Cry® 3 Special Edition   2006-05-23  19.99   6550.0
4      Devil May Cry® 3 Special Edition   2006-05-23  19.99   6550.0
...                                 ...          ...    ...      ...
36573    Counter-Strike: Condition Zero   2004-03-01   9.99     80.0
36574    Counter-Strike: Condition Zero   2004-03-01   9.99     80.0
36575    Counter-Strike: Condition Zero   2004-03-01   9.99     80.0
36576    Counter-Strike: Condition Zero   2004-03-01   9.99     80.0
36577    Counter-Strike: Condition Zero   2004-03-01   9.99     80.0

                                      developer                  user_id  \
0      Crystal Dynamics,Feral Interactive (Mac)        76561198052998873
1                              CAPCOM Co., Ltd.              ryanflyin13
2                              CAPCOM Co., Ltd.            SambaWarKiddo
3                              CAPCOM Co., Ltd.        76561198104824869
4                              CAPCOM Co., Ltd.        76561198096849086
...                                         ...                      ...
36573                                     Valve        76561198015050660
36574                                     Valve        76561198023508728
36575                                     Valve                 green290
36576                                     Valve  174gamecuman700kngkakak
36577                                     Valve                   lachwe

       playtime_forever                     posted  recommend  \
0                 378.0  Posted December 11, 2015.       True
1                2872.0             Posted June 4.       True
2                  47.0       Posted May 31, 2014.       True
3                4169.0  Posted February 22, 2014.       True
4                 776.0       Posted July 1, 2014.       True
...                 ...                        ...        ...
36573            2416.0  Posted December 23, 2014.      False
36574              15.0   Posted October 26, 2014.      False
36575             442.0    Posted January 5, 2015.       True
36576              72.0   Posted October 31, 2014.       True
36577              62.0        Posted May 4, 2015.       True

                                                  review  Sentiment_analysis  \
0      One of the best games of all time, I have been...                   2
1      This game made a huge impact on my life when i...                   1
2      Fantastic game by absolutely all means, and if...                   2
3      虽然不支持控制器和不能全银幕的游戏，但并不会减少游戏的可玩性和热趣，你依然可以灵活的进行华丽...                   1
4      .Una compra recomendada para los que les gusta...                   1
...                                                  ...                 ...
36573  作為第一個在steam入手的遊戲，老實說當初是為了1.6來順便帶回來，由於當時網路不太穩的關...                   1
36574                                      i caused 9/11                   1
36575  This game was suprisingly my first FPS game.11...                   2
36576                                                 :v                   1
36577  Random enemies popping out of no where will ma...                   0

         Años
0      2007.0
1      2006.0
2      2006.0
3      2006.0
4      2006.0
...       ...
36573  2004.0
36574  2004.0
36575  2004.0
36576  2004.0
36577  2004.0

[36578 rows x 14 columns]

In [98]:
modelo = df_merge.head(4000)

In [99]:
modelo.to_parquet('modelo.parquet', index=False)

Se guarda el CSV final luego de todo el Preprocesamiento de los datos

In [95]:
df_merge.to_parquet('df_merge.parquet', index=False)